### ISSUE TITLE
Error: Could not resolve app package: @apache-mynewt-core/apps/boot

### ISSUE THREAD

**Issue by OTLabs** [apache/mynewt-core#1948] opened 2019-08-06 21:37 UTC
I use latest `newt` 1.7.0 on Windows to build `rbnano2_boot` target and get follwoing error:

```
$ newt version
Apache Newt
   Version: 1.7.0
  Git Hash: 80bcba7
Build Date: 2019-07-17_13:51

$ newt build rbnano2_boot
Building target targets/rbnano2_boot
Error: Could not resolve app package: @apache-mynewt-core/apps/boot
```

**Comment by utzig** [comment] 2019-08-06 22:12
If you have a recent tree of Mynewt you have to change to boot app, using something like: `newt target set rbnano2_boot app=@mcuboot/boot/mynewt`.

**Comment by OTLabs** [comment] 2019-08-07 13:48
Implementing this setting I got the build running and successfully build the target, thank you!

I was following step-by-step the Tutorial | Project Blinky | Blinky on RedBear Nano 2 (version: latest, https://mynewt.apache.org/latest/tutorials/blinky/rbnano2.html). I would quite appreciate if the latest documentation can reflect this change in settings.

**Comment by utzig** [comment] 2019-08-07 17:32
Done here: https://github.com/apache/mynewt-documentation/pull/76

**Comment by OTLabs** [comment] 2019-08-07 19:06
Thanks a lot!

**Comment by utzig** [comment] 2019-08-09 17:36
This was fixed with apache/mynewt-documentation#76

**Closed by utzig** 2019-08-09 17:36 UTC

**Comment by brainstorm** [comment] 2019-11-01 07:38
I'm facing this same issue with this repo:

https://github.com/chris-zen/mdp-link-mynewt

And mynewt HEAD installed with Homebrew:

```shell
$ newt build nrf52_boot
Downloading repository mynewt-core (commit: master) from https://github.com/apache/mynewt-core.git
Downloading repository mynewt_nrf52840_mdk (commit: master) from https://github.com/makerdiary/mynewt_nrf52840_mdk.git
Downloading repository tinyusb (commit: master) from https://github.com/hathach/tinyusb.git
Building target targets/nrf52_boot
Error: Could not resolve app package: @mcuboot/boot/mynewt
```

Also with the arm-eabi toolchain outlined on issue #2076, from ArmMbed. I tried following the updated docs, using `set` for the bst and the `optimized` compile profile, but I get the same effect.

Are you able to reproduce this issue, @utzig?

**Comment by utzig** [comment] 2019-11-01 10:02
@brainstorm Yes, I could reproduce. There's many things that could be going wrong here. But doing `newt upgrade -f` afterwards solved it (not that it should be happening in the first place!). Also a very recent build of `newt` is required, because of a known bug in `git` submodules that `newt` is currently "masking" for the mcuboot repo.

**Comment by Thilanka97** [comment] 2020-02-12 03:28
hey @brainstorm , @utzig I am facing the same problem with blinky project.
 _**Could not resolve app package: @mcuboot/boot/mynewt**_

 I tried _**newt upgrade -f**_ as you suggested but I am getting following error with that cmd. 
_**Error: usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]**_

What is wrong here. I have already installed git as well.  Please help me to solve this problem. 

Thanks in advance!

**Comment by brainstorm** [comment] 2020-02-23 12:03
@Thilanka97 I'm not sure if it's entirely related, but there are some ongoing efforts to fix those issues in https://github.com/apache/mynewt-core/issues/2125... I would come back when 2.0 is properly merged/tested/released, IMHO.
